#import "./fragments/PostMediaBlockData.gql"

query SearchResults($in: [ID]) {
  contentNodes(where: { in: $in }) {
    nodes {
      ...PostMediaBlockData
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
