fragment PostMediaBlockData on ContentNode {
  slug
  uri
  ... on NodeWithExcerpt {
    excerpt
  }
  ... on NodeWithFeaturedImage {
    featuredImage {
      node {
        altText
        srcMedium: sourceUrl(size: MEDIUM)
        slug
      }
    }
  }
  ... on NodeWithTitle {
    title
  }
  ... on Page {
    seo {
      metaDesc
    }
  }
  ... on Post {
    categories(where: { exclude: 154 }) {
      nodes {
        name
        uri
      }
    }
  }
}
